### ISSUE TITLE
Express 4.x compatible

### ISSUE THREAD

**Issue by zumoshi** [nlf/connect-mysql#23]
hi , I tried to use your module with "express": "~4.0.0" , it gave the following error and crashed , works fine with express 3.x .

```
Error: Most middleware (like session) is no longer bundled with Express and must
 be installed separately. Please see https://github.com/senchalabs/connect#middleware.
    at Function.Object.defineProperty.get (C:\w\zbigo\node_modules\express\lib\express.js:89:13)
    at module.exports (C:\w\zbigo\node_modules\connect-mysql\lib\connect-mysql.js:19:24)
    at Object.<anonymous> (C:\w\zbigo\nsc.js:22:44)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\w\zbigo\https.js:20:11)
DEBUG: Program node https.js exited with code 8
```

the code used : 

```
var express = require('express')            //http://expressjs.com
,app = express()
, _e_cookieParser=require('cookie-parser')    //https://github.com/expressjs/cookie-parser
, _e_expressSession=require('express-session')  //https://github.com/expressjs/session
, _e_expressSStore=require('connect-mysql')(express) //https://github.com/nlf/connect-mysql
, mysql = require('mysql')                      //https://github.com/felixge/node-mysql
, pool  = mysql.createPool(conf.db)
app.use(_e_cookieParser());
app.use(_e_expressSession({secret:'--mysecret--',store:new _e_expressSStore({pool:mspool})}));
```

**Comment by thomasbaldwin** [comment]
@zumoshi did you ever get this working? I'm having a similar issue?
