### ISSUE TITLE
Error in cleanup query

### ISSUE THREAD

**Issue by danielsharvey** [nlf/connect-mysql#51]
I was finding that pooled session queries were being lost from the session pool.

It turns out that the cleanup query is wrong (has been wrong for a while :)) but the error was not reported due to the way the scheduling occurred.

The cleanup query references the field `id` whereas it should reference `sid`.

The error is:
```
error { Error: ER_BAD_FIELD_ERROR: Unknown column 'id' in 'field list'
    at Query.Sequence._packetToError (/home/ovmp/apps/ov-manufacture-planning/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/home/ovmp/apps/ov-manufacture-planning/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/home/ovmp/apps/ov-manufacture-planning/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/home/ovmp/apps/ov-manufacture-planning/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/home/ovmp/apps/ov-manufacture-planning/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/home/ovmp/apps/ov-manufacture-planning/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/home/ovmp/apps/ov-manufacture-planning/node_modules/mysql/lib/Connection.js:502:10)
    at Socket.emit (events.js:197:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:145:17)
    --------------------
    at Protocol._enqueue (/home/ovmp/apps/ov-manufacture-planning/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at PoolConnection.query (/home/ovmp/apps/ov-manufacture-planning/node_modules/mysql/lib/Connection.js:200:25)
    at /home/ovmp/apps/ov-manufacture-planning/node_modules/connect-mysql/lib/connect-mysql.js:216:20
    at execute (/home/ovmp/apps/ov-manufacture-planning/node_modules/connect-mysql/lib/connect-mysql.js:320:11)
    at /home/ovmp/apps/ov-manufacture-planning/node_modules/connect-mysql/lib/connect-mysql.js:334:22
    at Ping.onOperationComplete (/home/ovmp/apps/ov-manufacture-planning/node_modules/mysql/lib/Pool.js:111:5)
    at Ping.<anonymous> (/home/ovmp/apps/ov-manufacture-planning/node_modules/mysql/lib/Connection.js:502:10)
    at Ping._callback (/home/ovmp/apps/ov-manufacture-planning/node_modules/mysql/lib/Connection.js:468:16)
    at Ping.Sequence.end (/home/ovmp/apps/ov-manufacture-planning/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Ping.Sequence.OkPacket (/home/ovmp/apps/ov-manufacture-planning/node_modules/mysql/lib/protocol/sequences/Sequence.js:92:8)
    at Protocol._parsePacket (/home/ovmp/apps/ov-manufacture-planning/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/home/ovmp/apps/ov-manufacture-planning/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/home/ovmp/apps/ov-manufacture-planning/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/home/ovmp/apps/ov-manufacture-planning/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/home/ovmp/apps/ov-manufacture-planning/node_modules/mysql/lib/Connection.js:502:10)
    at Socket.emit (events.js:197:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:145:17)
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlMessage: "Unknown column 'id' in 'field list'",
  sqlState: '42S22',
  index: 0,
  sql:
   'DELETE FROM `sessions` WHERE id IN (SELECT temp.id FROM (SELECT `id` FROM `sessions` WHERE `expires` > 0 AND `expires` < UNIX_TIMESTAMP()) AS temp);' }
```

PR to follow.

**Comment by jas-** [comment]
@danielsharvey Thanks for reporting this. I should really create a test harness for this module to catch bugs like this. Can you confirm resolution in `v2.2.5`?

**Comment by danielsharvey** [comment]
@jas-, fixed confirmed thanks. Any particular reason for introducing `v` prefix in the version in `package.json`?

**Comment by jas-** [comment]
Not really. Maybe next version I will drop it. Thanks for confirming
